global:
  loglevel: debug
  http: ":9040"

rtsp:
  pull:
    live/test: rtsp://admin:@192.168.6.42:554/ch0_0.264

snapshot:
  enable: true
  savePath: "/home/torque/Vitan_Github/monibuca/example/custom/snapshots"
  frameRate: 10.0
  streamKey: "live/test"